// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: internal/protocol/grpc/proto/chimera.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChimeraService_Publish_FullMethodName      = "/chimera.v1.ChimeraService/Publish"
	ChimeraService_PublishBatch_FullMethodName = "/chimera.v1.ChimeraService/PublishBatch"
	ChimeraService_Consume_FullMethodName      = "/chimera.v1.ChimeraService/Consume"
	ChimeraService_CreateTopic_FullMethodName  = "/chimera.v1.ChimeraService/CreateTopic"
	ChimeraService_DeleteTopic_FullMethodName  = "/chimera.v1.ChimeraService/DeleteTopic"
	ChimeraService_GetTopicInfo_FullMethodName = "/chimera.v1.ChimeraService/GetTopicInfo"
	ChimeraService_Health_FullMethodName       = "/chimera.v1.ChimeraService/Health"
)

// ChimeraServiceClient is the client API for ChimeraService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChimeraMQ is a unified message queue and event streaming platform.
// The gRPC API provides bidirectional streaming for publish and consume operations.
type ChimeraServiceClient interface {
	// Publish a single message to a topic.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Publish multiple messages in a batch.
	PublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error)
	// Consume messages from a topic with offset tracking.
	// Client sends ConsumeRequest (subscribe/fetch/ack), server streams messages.
	Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error)
	// Create a new topic.
	CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error)
	// Delete a topic.
	DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error)
	// Get topic information.
	GetTopicInfo(ctx context.Context, in *GetTopicInfoRequest, opts ...grpc.CallOption) (*GetTopicInfoResponse, error)
	// Health check.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type chimeraServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChimeraServiceClient(cc grpc.ClientConnInterface) ChimeraServiceClient {
	return &chimeraServiceClient{cc}
}

func (c *chimeraServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, ChimeraService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chimeraServiceClient) PublishBatch(ctx context.Context, in *PublishBatchRequest, opts ...grpc.CallOption) (*PublishBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishBatchResponse)
	err := c.cc.Invoke(ctx, ChimeraService_PublishBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chimeraServiceClient) Consume(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChimeraService_ServiceDesc.Streams[0], ChimeraService_Consume_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConsumeRequest, ConsumeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChimeraService_ConsumeClient = grpc.BidiStreamingClient[ConsumeRequest, ConsumeResponse]

func (c *chimeraServiceClient) CreateTopic(ctx context.Context, in *CreateTopicRequest, opts ...grpc.CallOption) (*CreateTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopicResponse)
	err := c.cc.Invoke(ctx, ChimeraService_CreateTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chimeraServiceClient) DeleteTopic(ctx context.Context, in *DeleteTopicRequest, opts ...grpc.CallOption) (*DeleteTopicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTopicResponse)
	err := c.cc.Invoke(ctx, ChimeraService_DeleteTopic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chimeraServiceClient) GetTopicInfo(ctx context.Context, in *GetTopicInfoRequest, opts ...grpc.CallOption) (*GetTopicInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopicInfoResponse)
	err := c.cc.Invoke(ctx, ChimeraService_GetTopicInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chimeraServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, ChimeraService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChimeraServiceServer is the server API for ChimeraService service.
// All implementations must embed UnimplementedChimeraServiceServer
// for forward compatibility.
//
// ChimeraMQ is a unified message queue and event streaming platform.
// The gRPC API provides bidirectional streaming for publish and consume operations.
type ChimeraServiceServer interface {
	// Publish a single message to a topic.
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Publish multiple messages in a batch.
	PublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error)
	// Consume messages from a topic with offset tracking.
	// Client sends ConsumeRequest (subscribe/fetch/ack), server streams messages.
	Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error
	// Create a new topic.
	CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error)
	// Delete a topic.
	DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error)
	// Get topic information.
	GetTopicInfo(context.Context, *GetTopicInfoRequest) (*GetTopicInfoResponse, error)
	// Health check.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedChimeraServiceServer()
}

// UnimplementedChimeraServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChimeraServiceServer struct{}

func (UnimplementedChimeraServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedChimeraServiceServer) PublishBatch(context.Context, *PublishBatchRequest) (*PublishBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishBatch not implemented")
}
func (UnimplementedChimeraServiceServer) Consume(grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]) error {
	return status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedChimeraServiceServer) CreateTopic(context.Context, *CreateTopicRequest) (*CreateTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopic not implemented")
}
func (UnimplementedChimeraServiceServer) DeleteTopic(context.Context, *DeleteTopicRequest) (*DeleteTopicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTopic not implemented")
}
func (UnimplementedChimeraServiceServer) GetTopicInfo(context.Context, *GetTopicInfoRequest) (*GetTopicInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopicInfo not implemented")
}
func (UnimplementedChimeraServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedChimeraServiceServer) mustEmbedUnimplementedChimeraServiceServer() {}
func (UnimplementedChimeraServiceServer) testEmbeddedByValue()                        {}

// UnsafeChimeraServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChimeraServiceServer will
// result in compilation errors.
type UnsafeChimeraServiceServer interface {
	mustEmbedUnimplementedChimeraServiceServer()
}

func RegisterChimeraServiceServer(s grpc.ServiceRegistrar, srv ChimeraServiceServer) {
	// If the following call panics, it indicates UnimplementedChimeraServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChimeraService_ServiceDesc, srv)
}

func _ChimeraService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChimeraService_PublishBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).PublishBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_PublishBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).PublishBatch(ctx, req.(*PublishBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChimeraService_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChimeraServiceServer).Consume(&grpc.GenericServerStream[ConsumeRequest, ConsumeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChimeraService_ConsumeServer = grpc.BidiStreamingServer[ConsumeRequest, ConsumeResponse]

func _ChimeraService_CreateTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).CreateTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_CreateTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).CreateTopic(ctx, req.(*CreateTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChimeraService_DeleteTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).DeleteTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_DeleteTopic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).DeleteTopic(ctx, req.(*DeleteTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChimeraService_GetTopicInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopicInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).GetTopicInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_GetTopicInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).GetTopicInfo(ctx, req.(*GetTopicInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChimeraService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChimeraServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChimeraService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChimeraServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChimeraService_ServiceDesc is the grpc.ServiceDesc for ChimeraService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChimeraService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chimera.v1.ChimeraService",
	HandlerType: (*ChimeraServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _ChimeraService_Publish_Handler,
		},
		{
			MethodName: "PublishBatch",
			Handler:    _ChimeraService_PublishBatch_Handler,
		},
		{
			MethodName: "CreateTopic",
			Handler:    _ChimeraService_CreateTopic_Handler,
		},
		{
			MethodName: "DeleteTopic",
			Handler:    _ChimeraService_DeleteTopic_Handler,
		},
		{
			MethodName: "GetTopicInfo",
			Handler:    _ChimeraService_GetTopicInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _ChimeraService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _ChimeraService_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/protocol/grpc/proto/chimera.proto",
}
