// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/protocol/grpc/proto/chimera.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,3,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	TtlMs         int64                  `protobuf:"varint,5,opt,name=ttl_ms,json=ttlMs,proto3" json:"ttl_ms,omitempty"`
	DeliverAtMs   int64                  `protobuf:"varint,6,opt,name=deliver_at_ms,json=deliverAtMs,proto3" json:"deliver_at_ms,omitempty"`
	Headers       map[string][]byte      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   string                 `protobuf:"bytes,8,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *PublishRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PublishRequest) GetTtlMs() int64 {
	if x != nil {
		return x.TtlMs
	}
	return 0
}

func (x *PublishRequest) GetDeliverAtMs() int64 {
	if x != nil {
		return x.DeliverAtMs
	}
	return 0
}

func (x *PublishRequest) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *PublishRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishResponse) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PublishResponse) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PublishRequest      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{2}
}

func (x *PublishBatchRequest) GetMessages() []*PublishRequest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type BatchPublishResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPublishResult) Reset() {
	*x = BatchPublishResult{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPublishResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPublishResult) ProtoMessage() {}

func (x *BatchPublishResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPublishResult.ProtoReflect.Descriptor instead.
func (*BatchPublishResult) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{3}
}

func (x *BatchPublishResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BatchPublishResult) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *BatchPublishResult) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type PublishBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*BatchPublishResult  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	SuccessCount  int32                  `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	FailureCount  int32                  `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchResponse) Reset() {
	*x = PublishBatchResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchResponse) ProtoMessage() {}

func (x *PublishBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchResponse.ProtoReflect.Descriptor instead.
func (*PublishBatchResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{4}
}

func (x *PublishBatchResponse) GetResults() []*BatchPublishResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PublishBatchResponse) GetSuccessCount() int32 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *PublishBatchResponse) GetFailureCount() int32 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

type ConsumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ConsumeRequest_Subscribe
	//	*ConsumeRequest_Fetch
	//	*ConsumeRequest_Ack
	//	*ConsumeRequest_Nack
	//	*ConsumeRequest_CommitOffset
	//	*ConsumeRequest_Unsubscribe
	Action        isConsumeRequest_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeRequest) GetAction() isConsumeRequest_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ConsumeRequest) GetSubscribe() *SubscribeRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *ConsumeRequest) GetFetch() *FetchRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_Fetch); ok {
			return x.Fetch
		}
	}
	return nil
}

func (x *ConsumeRequest) GetAck() *AckRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ConsumeRequest) GetNack() *NackRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_Nack); ok {
			return x.Nack
		}
	}
	return nil
}

func (x *ConsumeRequest) GetCommitOffset() *CommitOffsetRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_CommitOffset); ok {
			return x.CommitOffset
		}
	}
	return nil
}

func (x *ConsumeRequest) GetUnsubscribe() *UnsubscribeRequest {
	if x != nil {
		if x, ok := x.Action.(*ConsumeRequest_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

type isConsumeRequest_Action interface {
	isConsumeRequest_Action()
}

type ConsumeRequest_Subscribe struct {
	Subscribe *SubscribeRequest `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type ConsumeRequest_Fetch struct {
	Fetch *FetchRequest `protobuf:"bytes,2,opt,name=fetch,proto3,oneof"`
}

type ConsumeRequest_Ack struct {
	Ack *AckRequest `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type ConsumeRequest_Nack struct {
	Nack *NackRequest `protobuf:"bytes,4,opt,name=nack,proto3,oneof"`
}

type ConsumeRequest_CommitOffset struct {
	CommitOffset *CommitOffsetRequest `protobuf:"bytes,5,opt,name=commit_offset,json=commitOffset,proto3,oneof"`
}

type ConsumeRequest_Unsubscribe struct {
	Unsubscribe *UnsubscribeRequest `protobuf:"bytes,6,opt,name=unsubscribe,proto3,oneof"`
}

func (*ConsumeRequest_Subscribe) isConsumeRequest_Action() {}

func (*ConsumeRequest_Fetch) isConsumeRequest_Action() {}

func (*ConsumeRequest_Ack) isConsumeRequest_Action() {}

func (*ConsumeRequest_Nack) isConsumeRequest_Action() {}

func (*ConsumeRequest_CommitOffset) isConsumeRequest_Action() {}

func (*ConsumeRequest_Unsubscribe) isConsumeRequest_Action() {}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // empty for stream mode, set for consumer group mode
	StartOffset   uint64                 `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SubscribeRequest) GetStartOffset() uint64 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxMessages   int32                  `protobuf:"varint,1,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{7}
}

func (x *FetchRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{8}
}

func (x *AckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AckRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Requeue       bool                   `protobuf:"varint,4,opt,name=requeue,proto3" json:"requeue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{9}
}

func (x *NackRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NackRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *NackRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NackRequest) GetRequeue() bool {
	if x != nil {
		return x.Requeue
	}
	return false
}

type CommitOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetRequest) Reset() {
	*x = CommitOffsetRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetRequest) ProtoMessage() {}

func (x *CommitOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{10}
}

func (x *CommitOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitOffsetRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CommitOffsetRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeRequest) Reset() {
	*x = UnsubscribeRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeRequest) ProtoMessage() {}

func (x *UnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{11}
}

func (x *UnsubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type ConsumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ConsumeResponse_Message
	//	*ConsumeResponse_Heartbeat
	//	*ConsumeResponse_Error
	Event         isConsumeResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeResponse) GetEvent() isConsumeResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ConsumeResponse) GetMessage() *Message {
	if x != nil {
		if x, ok := x.Event.(*ConsumeResponse_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *ConsumeResponse) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Event.(*ConsumeResponse_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ConsumeResponse) GetError() *ErrorInfo {
	if x != nil {
		if x, ok := x.Event.(*ConsumeResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isConsumeResponse_Event interface {
	isConsumeResponse_Event()
}

type ConsumeResponse_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

type ConsumeResponse_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ConsumeResponse_Error struct {
	Error *ErrorInfo `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ConsumeResponse_Message) isConsumeResponse_Event() {}

func (*ConsumeResponse_Heartbeat) isConsumeResponse_Event() {}

func (*ConsumeResponse_Error) isConsumeResponse_Event() {}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	MessageId     []byte                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // UUIDv7 (16 bytes)
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	RoutingKey    string                 `protobuf:"bytes,6,opt,name=routing_key,json=routingKey,proto3" json:"routing_key,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Headers       map[string][]byte      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType   string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"`
	SchemaId      uint32                 `protobuf:"varint,11,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{13}
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *Message) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Message) GetMessageId() []byte {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *Message) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Message) GetRoutingKey() string {
	if x != nil {
		return x.RoutingKey
	}
	return ""
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetHeaders() map[string][]byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetSchemaId() uint32 {
	if x != nil {
		return x.SchemaId
	}
	return 0
}

type Heartbeat struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ServerTimestampMs int64                  `protobuf:"varint,1,opt,name=server_timestamp_ms,json=serverTimestampMs,proto3" json:"server_timestamp_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{14}
}

func (x *Heartbeat) GetServerTimestampMs() int64 {
	if x != nil {
		return x.ServerTimestampMs
	}
	return 0
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{15}
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type TopicConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "queue", "stream", or "unified"
	Partitions     uint32                 `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	RetentionMs    int64                  `protobuf:"varint,4,opt,name=retention_ms,json=retentionMs,proto3" json:"retention_ms,omitempty"`
	MaxSegmentSize int64                  `protobuf:"varint,5,opt,name=max_segment_size,json=maxSegmentSize,proto3" json:"max_segment_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopicConfig) Reset() {
	*x = TopicConfig{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicConfig) ProtoMessage() {}

func (x *TopicConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicConfig.ProtoReflect.Descriptor instead.
func (*TopicConfig) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{16}
}

func (x *TopicConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TopicConfig) GetPartitions() uint32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

func (x *TopicConfig) GetRetentionMs() int64 {
	if x != nil {
		return x.RetentionMs
	}
	return 0
}

func (x *TopicConfig) GetMaxSegmentSize() int64 {
	if x != nil {
		return x.MaxSegmentSize
	}
	return 0
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TopicConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTopicRequest) GetConfig() *TopicConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       bool                   `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Config        *TopicConfig           `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{18}
}

func (x *CreateTopicResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *CreateTopicResponse) GetConfig() *TopicConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type DeleteTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type DeleteTopicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteTopicResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type GetTopicInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicInfoRequest) Reset() {
	*x = GetTopicInfoRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicInfoRequest) ProtoMessage() {}

func (x *GetTopicInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTopicInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{21}
}

func (x *GetTopicInfoRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type PartitionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HeadOffset    uint64                 `protobuf:"varint,2,opt,name=head_offset,json=headOffset,proto3" json:"head_offset,omitempty"`
	TailOffset    uint64                 `protobuf:"varint,3,opt,name=tail_offset,json=tailOffset,proto3" json:"tail_offset,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{22}
}

func (x *PartitionInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PartitionInfo) GetHeadOffset() uint64 {
	if x != nil {
		return x.HeadOffset
	}
	return 0
}

func (x *PartitionInfo) GetTailOffset() uint64 {
	if x != nil {
		return x.TailOffset
	}
	return 0
}

func (x *PartitionInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type GetTopicInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TopicConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicInfoResponse) Reset() {
	*x = GetTopicInfoResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicInfoResponse) ProtoMessage() {}

func (x *GetTopicInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTopicInfoResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{23}
}

func (x *GetTopicInfoResponse) GetConfig() *TopicConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetTopicInfoResponse) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{24}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UptimeMs      int64                  `protobuf:"varint,3,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_grpc_proto_chimera_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP(), []int{25}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() int64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

var File_internal_protocol_grpc_proto_chimera_proto protoreflect.FileDescriptor

const file_internal_protocol_grpc_proto_chimera_proto_rawDesc = "" +
	"\n" +
	"*internal/protocol/grpc/proto/chimera.proto\x12\n" +
	"chimera.v1\"\xda\x02\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1f\n" +
	"\vrouting_key\x18\x03 \x01(\tR\n" +
	"routingKey\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12\x15\n" +
	"\x06ttl_ms\x18\x05 \x01(\x03R\x05ttlMs\x12\"\n" +
	"\rdeliver_at_ms\x18\x06 \x01(\x03R\vdeliverAtMs\x12A\n" +
	"\aheaders\x18\a \x03(\v2'.chimera.v1.PublishRequest.HeadersEntryR\aheaders\x12!\n" +
	"\fcontent_type\x18\b \x01(\tR\vcontentType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"b\n" +
	"\x0fPublishResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"M\n" +
	"\x13PublishBatchRequest\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.chimera.v1.PublishRequestR\bmessages\"_\n" +
	"\x12BatchPublishResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"\x9a\x01\n" +
	"\x14PublishBatchResponse\x128\n" +
	"\aresults\x18\x01 \x03(\v2\x1e.chimera.v1.BatchPublishResultR\aresults\x12#\n" +
	"\rsuccess_count\x18\x02 \x01(\x05R\fsuccessCount\x12#\n" +
	"\rfailure_count\x18\x03 \x01(\x05R\ffailureCount\"\xf1\x02\n" +
	"\x0eConsumeRequest\x12<\n" +
	"\tsubscribe\x18\x01 \x01(\v2\x1c.chimera.v1.SubscribeRequestH\x00R\tsubscribe\x120\n" +
	"\x05fetch\x18\x02 \x01(\v2\x18.chimera.v1.FetchRequestH\x00R\x05fetch\x12*\n" +
	"\x03ack\x18\x03 \x01(\v2\x16.chimera.v1.AckRequestH\x00R\x03ack\x12-\n" +
	"\x04nack\x18\x04 \x01(\v2\x17.chimera.v1.NackRequestH\x00R\x04nack\x12F\n" +
	"\rcommit_offset\x18\x05 \x01(\v2\x1f.chimera.v1.CommitOffsetRequestH\x00R\fcommitOffset\x12B\n" +
	"\vunsubscribe\x18\x06 \x01(\v2\x1e.chimera.v1.UnsubscribeRequestH\x00R\vunsubscribeB\b\n" +
	"\x06action\"f\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x04R\vstartOffset\"1\n" +
	"\fFetchRequest\x12!\n" +
	"\fmax_messages\x18\x01 \x01(\x05R\vmaxMessages\"U\n" +
	"\n" +
	"AckRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"p\n" +
	"\vNackRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x18\n" +
	"\arequeue\x18\x04 \x01(\bR\arequeue\"^\n" +
	"\x13CommitOffsetRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"*\n" +
	"\x12UnsubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\xb1\x01\n" +
	"\x0fConsumeResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x13.chimera.v1.MessageH\x00R\amessage\x125\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.chimera.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\x05error\x18\x03 \x01(\v2\x15.chimera.v1.ErrorInfoH\x00R\x05errorB\a\n" +
	"\x05event\"\xab\x03\n" +
	"\aMessage\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\fR\tmessageId\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\x12\x1f\n" +
	"\vrouting_key\x18\x06 \x01(\tR\n" +
	"routingKey\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12:\n" +
	"\aheaders\x18\b \x03(\v2 .chimera.v1.Message.HeadersEntryR\aheaders\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12\x18\n" +
	"\apayload\x18\n" +
	" \x01(\fR\apayload\x12\x1b\n" +
	"\tschema_id\x18\v \x01(\rR\bschemaId\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\";\n" +
	"\tHeartbeat\x12.\n" +
	"\x13server_timestamp_ms\x18\x01 \x01(\x03R\x11serverTimestampMs\"9\n" +
	"\tErrorInfo\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xa2\x01\n" +
	"\vTopicConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\rR\n" +
	"partitions\x12!\n" +
	"\fretention_ms\x18\x04 \x01(\x03R\vretentionMs\x12(\n" +
	"\x10max_segment_size\x18\x05 \x01(\x03R\x0emaxSegmentSize\"E\n" +
	"\x12CreateTopicRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.chimera.v1.TopicConfigR\x06config\"`\n" +
	"\x13CreateTopicResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\bR\acreated\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.chimera.v1.TopicConfigR\x06config\"*\n" +
	"\x12DeleteTopicRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"/\n" +
	"\x13DeleteTopicResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"+\n" +
	"\x13GetTopicInfoRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\x80\x01\n" +
	"\rPartitionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vhead_offset\x18\x02 \x01(\x04R\n" +
	"headOffset\x12\x1f\n" +
	"\vtail_offset\x18\x03 \x01(\x04R\n" +
	"tailOffset\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"\x82\x01\n" +
	"\x14GetTopicInfoResponse\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.chimera.v1.TopicConfigR\x06config\x129\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x19.chimera.v1.PartitionInfoR\n" +
	"partitions\"\x0f\n" +
	"\rHealthRequest\"a\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\tuptime_ms\x18\x03 \x01(\x03R\buptimeMs2\xa3\x04\n" +
	"\x0eChimeraService\x12B\n" +
	"\aPublish\x12\x1a.chimera.v1.PublishRequest\x1a\x1b.chimera.v1.PublishResponse\x12Q\n" +
	"\fPublishBatch\x12\x1f.chimera.v1.PublishBatchRequest\x1a .chimera.v1.PublishBatchResponse\x12F\n" +
	"\aConsume\x12\x1a.chimera.v1.ConsumeRequest\x1a\x1b.chimera.v1.ConsumeResponse(\x010\x01\x12N\n" +
	"\vCreateTopic\x12\x1e.chimera.v1.CreateTopicRequest\x1a\x1f.chimera.v1.CreateTopicResponse\x12N\n" +
	"\vDeleteTopic\x12\x1e.chimera.v1.DeleteTopicRequest\x1a\x1f.chimera.v1.DeleteTopicResponse\x12Q\n" +
	"\fGetTopicInfo\x12\x1f.chimera.v1.GetTopicInfoRequest\x1a .chimera.v1.GetTopicInfoResponse\x12?\n" +
	"\x06Health\x12\x19.chimera.v1.HealthRequest\x1a\x1a.chimera.v1.HealthResponseB;Z9github.com/chimeramq/chimera/internal/protocol/grpc/protob\x06proto3"

var (
	file_internal_protocol_grpc_proto_chimera_proto_rawDescOnce sync.Once
	file_internal_protocol_grpc_proto_chimera_proto_rawDescData []byte
)

func file_internal_protocol_grpc_proto_chimera_proto_rawDescGZIP() []byte {
	file_internal_protocol_grpc_proto_chimera_proto_rawDescOnce.Do(func() {
		file_internal_protocol_grpc_proto_chimera_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_grpc_proto_chimera_proto_rawDesc), len(file_internal_protocol_grpc_proto_chimera_proto_rawDesc)))
	})
	return file_internal_protocol_grpc_proto_chimera_proto_rawDescData
}

var file_internal_protocol_grpc_proto_chimera_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_internal_protocol_grpc_proto_chimera_proto_goTypes = []any{
	(*PublishRequest)(nil),       // 0: chimera.v1.PublishRequest
	(*PublishResponse)(nil),      // 1: chimera.v1.PublishResponse
	(*PublishBatchRequest)(nil),  // 2: chimera.v1.PublishBatchRequest
	(*BatchPublishResult)(nil),   // 3: chimera.v1.BatchPublishResult
	(*PublishBatchResponse)(nil), // 4: chimera.v1.PublishBatchResponse
	(*ConsumeRequest)(nil),       // 5: chimera.v1.ConsumeRequest
	(*SubscribeRequest)(nil),     // 6: chimera.v1.SubscribeRequest
	(*FetchRequest)(nil),         // 7: chimera.v1.FetchRequest
	(*AckRequest)(nil),           // 8: chimera.v1.AckRequest
	(*NackRequest)(nil),          // 9: chimera.v1.NackRequest
	(*CommitOffsetRequest)(nil),  // 10: chimera.v1.CommitOffsetRequest
	(*UnsubscribeRequest)(nil),   // 11: chimera.v1.UnsubscribeRequest
	(*ConsumeResponse)(nil),      // 12: chimera.v1.ConsumeResponse
	(*Message)(nil),              // 13: chimera.v1.Message
	(*Heartbeat)(nil),            // 14: chimera.v1.Heartbeat
	(*ErrorInfo)(nil),            // 15: chimera.v1.ErrorInfo
	(*TopicConfig)(nil),          // 16: chimera.v1.TopicConfig
	(*CreateTopicRequest)(nil),   // 17: chimera.v1.CreateTopicRequest
	(*CreateTopicResponse)(nil),  // 18: chimera.v1.CreateTopicResponse
	(*DeleteTopicRequest)(nil),   // 19: chimera.v1.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),  // 20: chimera.v1.DeleteTopicResponse
	(*GetTopicInfoRequest)(nil),  // 21: chimera.v1.GetTopicInfoRequest
	(*PartitionInfo)(nil),        // 22: chimera.v1.PartitionInfo
	(*GetTopicInfoResponse)(nil), // 23: chimera.v1.GetTopicInfoResponse
	(*HealthRequest)(nil),        // 24: chimera.v1.HealthRequest
	(*HealthResponse)(nil),       // 25: chimera.v1.HealthResponse
	nil,                          // 26: chimera.v1.PublishRequest.HeadersEntry
	nil,                          // 27: chimera.v1.Message.HeadersEntry
}
var file_internal_protocol_grpc_proto_chimera_proto_depIdxs = []int32{
	26, // 0: chimera.v1.PublishRequest.headers:type_name -> chimera.v1.PublishRequest.HeadersEntry
	0,  // 1: chimera.v1.PublishBatchRequest.messages:type_name -> chimera.v1.PublishRequest
	3,  // 2: chimera.v1.PublishBatchResponse.results:type_name -> chimera.v1.BatchPublishResult
	6,  // 3: chimera.v1.ConsumeRequest.subscribe:type_name -> chimera.v1.SubscribeRequest
	7,  // 4: chimera.v1.ConsumeRequest.fetch:type_name -> chimera.v1.FetchRequest
	8,  // 5: chimera.v1.ConsumeRequest.ack:type_name -> chimera.v1.AckRequest
	9,  // 6: chimera.v1.ConsumeRequest.nack:type_name -> chimera.v1.NackRequest
	10, // 7: chimera.v1.ConsumeRequest.commit_offset:type_name -> chimera.v1.CommitOffsetRequest
	11, // 8: chimera.v1.ConsumeRequest.unsubscribe:type_name -> chimera.v1.UnsubscribeRequest
	13, // 9: chimera.v1.ConsumeResponse.message:type_name -> chimera.v1.Message
	14, // 10: chimera.v1.ConsumeResponse.heartbeat:type_name -> chimera.v1.Heartbeat
	15, // 11: chimera.v1.ConsumeResponse.error:type_name -> chimera.v1.ErrorInfo
	27, // 12: chimera.v1.Message.headers:type_name -> chimera.v1.Message.HeadersEntry
	16, // 13: chimera.v1.CreateTopicRequest.config:type_name -> chimera.v1.TopicConfig
	16, // 14: chimera.v1.CreateTopicResponse.config:type_name -> chimera.v1.TopicConfig
	16, // 15: chimera.v1.GetTopicInfoResponse.config:type_name -> chimera.v1.TopicConfig
	22, // 16: chimera.v1.GetTopicInfoResponse.partitions:type_name -> chimera.v1.PartitionInfo
	0,  // 17: chimera.v1.ChimeraService.Publish:input_type -> chimera.v1.PublishRequest
	2,  // 18: chimera.v1.ChimeraService.PublishBatch:input_type -> chimera.v1.PublishBatchRequest
	5,  // 19: chimera.v1.ChimeraService.Consume:input_type -> chimera.v1.ConsumeRequest
	17, // 20: chimera.v1.ChimeraService.CreateTopic:input_type -> chimera.v1.CreateTopicRequest
	19, // 21: chimera.v1.ChimeraService.DeleteTopic:input_type -> chimera.v1.DeleteTopicRequest
	21, // 22: chimera.v1.ChimeraService.GetTopicInfo:input_type -> chimera.v1.GetTopicInfoRequest
	24, // 23: chimera.v1.ChimeraService.Health:input_type -> chimera.v1.HealthRequest
	1,  // 24: chimera.v1.ChimeraService.Publish:output_type -> chimera.v1.PublishResponse
	4,  // 25: chimera.v1.ChimeraService.PublishBatch:output_type -> chimera.v1.PublishBatchResponse
	12, // 26: chimera.v1.ChimeraService.Consume:output_type -> chimera.v1.ConsumeResponse
	18, // 27: chimera.v1.ChimeraService.CreateTopic:output_type -> chimera.v1.CreateTopicResponse
	20, // 28: chimera.v1.ChimeraService.DeleteTopic:output_type -> chimera.v1.DeleteTopicResponse
	23, // 29: chimera.v1.ChimeraService.GetTopicInfo:output_type -> chimera.v1.GetTopicInfoResponse
	25, // 30: chimera.v1.ChimeraService.Health:output_type -> chimera.v1.HealthResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_protocol_grpc_proto_chimera_proto_init() }
func file_internal_protocol_grpc_proto_chimera_proto_init() {
	if File_internal_protocol_grpc_proto_chimera_proto != nil {
		return
	}
	file_internal_protocol_grpc_proto_chimera_proto_msgTypes[5].OneofWrappers = []any{
		(*ConsumeRequest_Subscribe)(nil),
		(*ConsumeRequest_Fetch)(nil),
		(*ConsumeRequest_Ack)(nil),
		(*ConsumeRequest_Nack)(nil),
		(*ConsumeRequest_CommitOffset)(nil),
		(*ConsumeRequest_Unsubscribe)(nil),
	}
	file_internal_protocol_grpc_proto_chimera_proto_msgTypes[12].OneofWrappers = []any{
		(*ConsumeResponse_Message)(nil),
		(*ConsumeResponse_Heartbeat)(nil),
		(*ConsumeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_grpc_proto_chimera_proto_rawDesc), len(file_internal_protocol_grpc_proto_chimera_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_grpc_proto_chimera_proto_goTypes,
		DependencyIndexes: file_internal_protocol_grpc_proto_chimera_proto_depIdxs,
		MessageInfos:      file_internal_protocol_grpc_proto_chimera_proto_msgTypes,
	}.Build()
	File_internal_protocol_grpc_proto_chimera_proto = out.File
	file_internal_protocol_grpc_proto_chimera_proto_goTypes = nil
	file_internal_protocol_grpc_proto_chimera_proto_depIdxs = nil
}
