global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: chimera
    static_configs:
      - targets:
          - chimera:9090
    metrics_path: /v1/metrics
    scrape_interval: 10s
