{{- if not .Values.auth.token.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chimera.fullname" . }}-token
  labels:
    {{- include "chimera.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-token: {{ .Values.auth.token.value | quote }}
{{- end }}
