apiVersion: v1
kind: Service
metadata:
  name: {{ include "chimera.fullname" . }}
  labels:
    {{- include "chimera.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.protocolPort }}
      targetPort: protocol
      protocol: TCP
      name: protocol
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "chimera.selectorLabels" . | nindent 4 }}
